# Generated by Django 3.2.6 on 2022-03-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
