# Generated by Django 3.2.6 on 2022-03-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
        ('loginapp', '0002_alter_userdetails_subscriptionplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='coach_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='subscriptionplan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerapp.planmodel'),
        ),
    ]
