# Generated by Django 3.2.6 on 2022-03-25 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
        ('loginapp', '0003_auto_20220325_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='coach_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='subscriptionplan_id',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managerapp.planmodel'),
        ),
    ]
