# Generated by Django 3.2.6 on 2022-03-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_rename_discription_planmodel_description'),
        ('loginapp', '0004_auto_20220325_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='subscriptionplan_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managerapp.planmodel'),
        ),
    ]
