# Generated by Django 3.2.6 on 2022-03-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coachapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetailsmodel',
            name='customer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdetailsmodel',
            name='d_plan',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coachapp.diet_planmodel'),
        ),
        migrations.AlterField(
            model_name='customerdetailsmodel',
            name='schedule',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coachapp.schedulemodel'),
        ),
    ]
