# Generated by Django 3.2.6 on 2022-03-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachapp', '0003_auto_20220325_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetailsmodel',
            name='d_plan',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coachapp.diet_planmodel'),
        ),
        migrations.AlterField(
            model_name='customerdetailsmodel',
            name='schedule',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coachapp.schedulemodel'),
        ),
    ]
